
export const AUTH_STACK_SCREEN = {
  SIGNUP: 'SIGNUP',
  LOGIN: 'LOGIN',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
};

export const BOTTOM_TAB_SCREENS = {
  HOME: 'HOME',
  SEARCH: 'SEARCH',
  FAVORITE: 'FAVORITE',
  CALENDAR: 'CALENDAR',
  PROFILE: 'PROFILE',
};

 
